apiVersion: v1
data:
  AWS_CLIENT_ID: {{ .Values.app.environment.AWS_CLIENT_ID }}
  AWS_CLIENT_SECRET: {{ .Values.app.environment.AWS_CLIENT_SECRET }}
  BUDGET_URL: http://budget.easytrip.svc.cluster.local:8080
  ISSUER_URI: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_ZuEoh6tm7
  MEMBER_URL: http://member.easytrip.svc.cluster.local:8083
  MONGODB_DATABASE: easytrip
  MONGODB_URI: mongodb://root:1234@mongo.easytrip.svc.cluster.local:27017
  PLAN_URL: http://plan.easytrip.svc.cluster.local:8081
  POST_URL: http://post.easytrip.svc.cluster.local:8085
  POSTGRES_PASSWORD: "1234"
  POSTGRES_URL: jdbc:postgresql://postgres.easytrip.svc.cluster.local:5432/easytrip
  POSTGRES_USER: postgres
  RABBITMQ_HOST: rabbitmq.easytrip.svc.cluster.local
  RABBITMQ_PASSWORD: test
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: test
  REDIS_HOST: redis.easytrip.svc.cluster.local
  REDIS_PASSWORD: test
  REDIS_PORT: "6379"
kind: ConfigMap
metadata:
  name: app-config
  namespace: easytrip