apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orchestration.environment.SERVICE_NAME }}
  namespace: {{ .Values.app.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.orchestration.environment.SERVER_PORT }}
    targetPort: {{ .Values.orchestration.environment.SERVER_PORT }}
  selector:
    app: {{ .Values.orchestration.environment.SERVICE_NAME }}